/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OpholdImport } from './routes/ophold'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OpholdRoute = OpholdImport.update({
  id: '/ophold',
  path: '/ophold',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ophold': {
      id: '/ophold'
      path: '/ophold'
      fullPath: '/ophold'
      preLoaderRoute: typeof OpholdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ophold': typeof OpholdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ophold': typeof OpholdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ophold': typeof OpholdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ophold'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ophold'
  id: '__root__' | '/' | '/ophold'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpholdRoute: typeof OpholdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpholdRoute: OpholdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/ophold"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/ophold": {
      "filePath": "ophold.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
